global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 2m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          service: 'prometheus'

  - job_name: 'node_exporter'
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          service: 'node'

  - job_name: 'mysql'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['mysql_exporter:9104']
        labels:
          service: 'mysql'

  - job_name: 'apache'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['apache_exporter:9117']
        labels:
          service: 'apache'

  - job_name: 'nginx'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['nginx_exporter:9113']
        labels:
          service: 'nginx'

